//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpagesProviderWebServices.ShopCountServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_ShopCount_SOAP", Namespace="urn://epages.de/WebService/ShopCountService/2006/08")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TShopCount))]
    public partial class ShopCountService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ShopCountService() {
            this.Url = "http://localhost/epages/Site.soap";
        }
        
        public ShopCountService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ShopCountService/2006/08#getCount", RequestNamespace="urn://epages.de/WebService/ShopCountService/2006/08", ResponseNamespace="urn://epages.de/WebService/ShopCountService/2006/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("Count")]
        public int getCount(type_GetCount_In Filter) {
            object[] results = this.Invoke("getCount", new object[] {
                        Filter});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCount(type_GetCount_In Filter, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCount", new object[] {
                        Filter}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndgetCount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ShopCountService/2006/08#getAllCounts", RequestNamespace="urn://epages.de/WebService/ShopCountService/2006/08", ResponseNamespace="urn://epages.de/WebService/ShopCountService/2006/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("AllCounts")]
        public TShopCount[] getAllCounts() {
            object[] results = this.Invoke("getAllCounts", new object[0]);
            return ((TShopCount[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllCounts(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllCounts", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TShopCount[] EndgetAllCounts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TShopCount[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ShopCountService/2006/08")]
    public partial class type_GetCount_In {
        
        /// <remarks/>
        public string ShopType;
        
        /// <remarks/>
        public string Database;
        
        /// <remarks/>
        public int IsClosed;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsClosedSpecified;
        
        /// <remarks/>
        public int IsTrialShop;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsTrialShopSpecified;
        
        /// <remarks/>
        public int IsInternalTestShop;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsInternalTestShopSpecified;
        
        /// <remarks/>
        public int IsPreCreated;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsPreCreatedSpecified;
        
        /// <remarks/>
        public int IsDeleted;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsDeletedSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ShopCountService/2006/08")]
    public partial class TShopCount {
        
        /// <remarks/>
        public string ShopType;
        
        /// <remarks/>
        public string Database;
        
        /// <remarks/>
        public int Trial_Closed;
        
        /// <remarks/>
        public int Trial_NotClosed;
        
        /// <remarks/>
        public int NotTrial_Closed;
        
        /// <remarks/>
        public int NotTrial_NotClosed;
        
        /// <remarks/>
        public int PreCreated;
    }
}
