//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpagesWebServices.ProductImageServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_ProductImage_SOAP", Namespace="urn://epages.de/WebService/ProductImageService/2006/03")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUploadScale_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpload_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TImageData))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TDelete_Return))]
    public partial class ProductImageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ProductImageService() {
            this.Url = "http://localhost/epages/Store.soap";
        }
        
        public ProductImageService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductImageService/2006/03#exists", RequestNamespace="urn://epages.de/WebService/ProductImageService/2006/03", ResponseNamespace="urn://epages.de/WebService/ProductImageService/2006/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Exists")]
        public bool exists(string TObjectPath, string TFileName) {
            object[] results = this.Invoke("exists", new object[] {
                        TObjectPath,
                        TFileName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexists(string TObjectPath, string TFileName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exists", new object[] {
                        TObjectPath,
                        TFileName}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endexists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductImageService/2006/03#delete", RequestNamespace="urn://epages.de/WebService/ProductImageService/2006/03", ResponseNamespace="urn://epages.de/WebService/ProductImageService/2006/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Files")]
        public TDelete_Return[] delete(string TObjectPath, string[] TListOfFileNames) {
            object[] results = this.Invoke("delete", new object[] {
                        TObjectPath,
                        TListOfFileNames});
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindelete(string TObjectPath, string[] TListOfFileNames, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("delete", new object[] {
                        TObjectPath,
                        TListOfFileNames}, callback, asyncState);
        }
        
        /// <remarks/>
        public TDelete_Return[] Enddelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductImageService/2006/03#upload", RequestNamespace="urn://epages.de/WebService/ProductImageService/2006/03", ResponseNamespace="urn://epages.de/WebService/ProductImageService/2006/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Files")]
        public TUpload_Return[] upload(string TObjectPath, TUpload_Input ImageData) {
            object[] results = this.Invoke("upload", new object[] {
                        TObjectPath,
                        ImageData});
            return ((TUpload_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupload(string TObjectPath, TUpload_Input ImageData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("upload", new object[] {
                        TObjectPath,
                        ImageData}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUpload_Return[] Endupload(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUpload_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductImageService/2006/03#uploadscale", RequestNamespace="urn://epages.de/WebService/ProductImageService/2006/03", ResponseNamespace="urn://epages.de/WebService/ProductImageService/2006/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Files")]
        public TUploadScale_Return[] uploadscale(string TObjectPath, TUploadScale_Input ImageData, TScaleParams ScaleParams) {
            object[] results = this.Invoke("uploadscale", new object[] {
                        TObjectPath,
                        ImageData,
                        ScaleParams});
            return ((TUploadScale_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginuploadscale(string TObjectPath, TUploadScale_Input ImageData, TScaleParams ScaleParams, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("uploadscale", new object[] {
                        TObjectPath,
                        ImageData,
                        ScaleParams}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUploadScale_Return[] Enduploadscale(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUploadScale_Return[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductImageTypes/2006/03")]
    public partial class TDelete_Return {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public bool deleted;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool deletedSpecified;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TError {
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductImageTypes/2006/03")]
    public partial class TUploadScale_Return {
        
        /// <remarks/>
        public bool WriteOK;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool WriteOKSpecified;
        
        /// <remarks/>
        public bool ScaleOK;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ScaleOKSpecified;
        
        /// <remarks/>
        public string File;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductImageTypes/2006/03")]
    public partial class TScaleParams {
        
        /// <remarks/>
        public bool SCALE_BORDER_IMAGE_h;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool SCALE_BORDER_IMAGE_hSpecified;
        
        /// <remarks/>
        public bool SCALE_BORDER_IMAGE_m;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool SCALE_BORDER_IMAGE_mSpecified;
        
        /// <remarks/>
        public string SCALE_BORDER_COLOR_h;
        
        /// <remarks/>
        public string SCALE_BORDER_COLOR_m;
        
        /// <remarks/>
        public string SCALE_NAME_h;
        
        /// <remarks/>
        public string SCALE_NAME_m;
        
        /// <remarks/>
        public string SCALE_NAME_s;
        
        /// <remarks/>
        public string SCALE_SIZE_h;
        
        /// <remarks/>
        public string SCALE_SIZE_m;
        
        /// <remarks/>
        public string SCALE_SIZE_s;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductImageTypes/2006/03")]
    public partial class TUploadScale_Input {
        
        /// <remarks/>
        public TImageData[] ImageData;
        
        /// <remarks/>
        public string ImagesSlideShowString;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductImageTypes/2006/03")]
    public partial class TImageData {
        
        /// <remarks/>
        public string FileName;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] Content;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductImageTypes/2006/03")]
    public partial class TUpload_Return {
        
        /// <remarks/>
        public bool WriteOK;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool WriteOKSpecified;
        
        /// <remarks/>
        public string File;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductImageTypes/2006/03")]
    public partial class TUpload_Input {
        
        /// <remarks/>
        public TImageData[] ImageData;
        
        /// <remarks/>
        public string ImagesSlideShowString;
    }
}
