//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpagesWebServices.CatalogService6Ref {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_Catalog_SOAP", Namespace="urn://epages.de/WebService/CatalogService/2011/03")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TImageData))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TSortProducts_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TSortProducts_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TDelete_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TExists_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAttribute))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TLocalizedValue))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetInfo_Return))]
    public partial class CatalogService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CatalogService() {
            this.Url = "http://localhost/epages/Store.soap";
        }
        
        public CatalogService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#getInfo", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TGetInfo_Return[] getInfo(string[] Catalogs, string[] Attributes, string[] LanguageCodes) {
            object[] results = this.Invoke("getInfo", new object[] {
                        Catalogs,
                        Attributes,
                        LanguageCodes});
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInfo(string[] Catalogs, string[] Attributes, string[] LanguageCodes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInfo", new object[] {
                        Catalogs,
                        Attributes,
                        LanguageCodes}, callback, asyncState);
        }
        
        /// <remarks/>
        public TGetInfo_Return[] EndgetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#exists", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TExists_Return[] exists(string[] Catalogs) {
            object[] results = this.Invoke("exists", new object[] {
                        Catalogs});
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexists(string[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exists", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TExists_Return[] Endexists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#delete", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TDelete_Return[] delete(string[] Catalogs) {
            object[] results = this.Invoke("delete", new object[] {
                        Catalogs});
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindelete(string[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("delete", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TDelete_Return[] Enddelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#update", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TUpdate_Return[] update(TUpdate_Input[] Catalogs) {
            object[] results = this.Invoke("update", new object[] {
                        Catalogs});
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate(TUpdate_Input[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUpdate_Return[] Endupdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#create", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TCreate_Return[] create(TCreate_Input[] Catalogs) {
            object[] results = this.Invoke("create", new object[] {
                        Catalogs});
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincreate(TCreate_Input[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("create", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TCreate_Return[] Endcreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#getRoot", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Root")]
        public TGetRoot_Return getRoot() {
            object[] results = this.Invoke("getRoot", new object[0]);
            return ((TGetRoot_Return)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRoot(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRoot", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TGetRoot_Return EndgetRoot(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetRoot_Return)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#sortProducts", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TSortProducts_Return[] sortProducts(TSortProducts_Input[] Catalogs) {
            object[] results = this.Invoke("sortProducts", new object[] {
                        Catalogs});
            return ((TSortProducts_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsortProducts(TSortProducts_Input[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sortProducts", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TSortProducts_Return[] EndsortProducts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TSortProducts_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#uploadImage", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Files")]
        public TUpload_Return uploadImage(string TObjectPath, TUpload_Input ImageData) {
            object[] results = this.Invoke("uploadImage", new object[] {
                        TObjectPath,
                        ImageData});
            return ((TUpload_Return)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginuploadImage(string TObjectPath, TUpload_Input ImageData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("uploadImage", new object[] {
                        TObjectPath,
                        ImageData}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUpload_Return EnduploadImage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUpload_Return)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2011/03#uploadImage", RequestNamespace="urn://epages.de/WebService/CatalogService/2011/03", ResponseNamespace="urn://epages.de/WebService/CatalogService/2011/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("Categories")]
        public string[] getCategories() {
            object[] results = this.Invoke("getCategories", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCategories(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCategories", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetCategories(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TGetInfo_Return {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public string Alias;
        
        /// <remarks/>
        public string Class;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position;
        
        /// <remarks/>
        public string ParentCatalog;
        
        /// <remarks/>
        public string WebUrl;
        
        /// <remarks/>
        public bool IsVisible;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsVisibleSpecified;
        
        /// <remarks/>
        public TLocalizedValue[] Name;
        
        /// <remarks/>
        public TLocalizedValue[] Text;
        
        /// <remarks/>
        public TLocalizedValue[] Text1;
        
        /// <remarks/>
        public TLocalizedValue[] Text2;
        
        /// <remarks/>
        public TLocalizedValue[] Text3;
        
        /// <remarks/>
        public TLocalizedValue[] URI;
        
        /// <remarks/>
        public TLocalizedValue[] CanonicalURL;
        
        /// <remarks/>
        public string[] SubCatalogs;
        
        /// <remarks/>
        public TAttribute[] TemplateTypes;
        
        /// <remarks/>
        public TAttribute[] Attributes;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TLocalizedValue {
        
        /// <remarks/>
        public string LanguageCode;
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TUpload_Return {
        
        /// <remarks/>
        public bool WriteOK;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool WriteOKSpecified;
        
        /// <remarks/>
        public string File;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TError {
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TImageData {
        
        /// <remarks/>
        public string FileName;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] Content;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TUpload_Input {
        
        /// <remarks/>
        public TImageData[] ImageData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TSortProducts_Return {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public bool sorted;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool sortedSpecified;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TSortProducts_Input {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public string sort;
        
        /// <remarks/>
        public bool allSub;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool allSubSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogService/2011/03")]
    public partial class TGetRoot_Return {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TCreate_Return {
        
        /// <remarks/>
        public string Alias;
        
        /// <remarks/>
        public string ParentCatalog;
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public bool created;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool createdSpecified;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TCreate_Input {
        
        /// <remarks/>
        public string Alias;
        
        /// <remarks/>
        public string ParentCatalog;
        
        /// <remarks/>
        public bool IsVisible;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsVisibleSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position;
        
        /// <remarks/>
        public TLocalizedValue[] Name;
        
        /// <remarks/>
        public TLocalizedValue[] Text;
        
        /// <remarks/>
        public TLocalizedValue[] Text1;
        
        /// <remarks/>
        public TLocalizedValue[] Text2;
        
        /// <remarks/>
        public TLocalizedValue[] Text3;
        
        /// <remarks/>
        public TLocalizedValue[] URI;
        
        /// <remarks/>
        public TAttribute[] TemplateTypes;
        
        /// <remarks/>
        public TAttribute[] Attributes;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TAttribute {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public TLocalizedValue[] LocalizedValues;
        
        /// <remarks/>
        public string Type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TUpdate_Return {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public bool updated;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool updatedSpecified;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TUpdate_Input {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public bool IsVisible;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsVisibleSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position;
        
        /// <remarks/>
        public TLocalizedValue[] Name;
        
        /// <remarks/>
        public TLocalizedValue[] Text;
        
        /// <remarks/>
        public TLocalizedValue[] Text1;
        
        /// <remarks/>
        public TLocalizedValue[] Text2;
        
        /// <remarks/>
        public TLocalizedValue[] Text3;
        
        /// <remarks/>
        public TLocalizedValue[] URI;
        
        /// <remarks/>
        public string MoveToParentCatalog;
        
        /// <remarks/>
        public TAttribute[] TemplateTypes;
        
        /// <remarks/>
        public TAttribute[] Attributes;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TDelete_Return {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public bool deleted;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool deletedSpecified;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2011/03")]
    public partial class TExists_Return {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        public bool exists;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool existsSpecified;
        
        /// <remarks/>
        public TError Error;
    }
}
