//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3053
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace EpagesWebServices.CustomerService3Ref {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_Customer_SOAP", Namespace="urn://epages.de/WebService/CustomerService/2007/08")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TDelete_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TExists_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TLocalizedValue))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAttribute))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetInfo_Return))]
    public partial class CustomerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback existsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback findOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerService() {
            this.Url = "http://localhost/epages/Store.soap";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getInfoCompletedEventHandler getInfoCompleted;
        
        /// <remarks/>
        public event existsCompletedEventHandler existsCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event findCompletedEventHandler findCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CustomerService/2007/08#getInfo", RequestNamespace="urn://epages.de/WebService/CustomerService/2007/08", ResponseNamespace="urn://epages.de/WebService/CustomerService/2007/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("Customers")]
        public TGetInfo_Return[] getInfo(string[] Customers, string[] Attributes, string[] AddressAttributes) {
            object[] results = this.Invoke("getInfo", new object[] {
                        Customers,
                        Attributes,
                        AddressAttributes});
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInfo(string[] Customers, string[] Attributes, string[] AddressAttributes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInfo", new object[] {
                        Customers,
                        Attributes,
                        AddressAttributes}, callback, asyncState);
        }
        
        /// <remarks/>
        public TGetInfo_Return[] EndgetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void getInfoAsync(string[] Customers, string[] Attributes, string[] AddressAttributes) {
            this.getInfoAsync(Customers, Attributes, AddressAttributes, null);
        }
        
        /// <remarks/>
        public void getInfoAsync(string[] Customers, string[] Attributes, string[] AddressAttributes, object userState) {
            if ((this.getInfoOperationCompleted == null)) {
                this.getInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInfoOperationCompleted);
            }
            this.InvokeAsync("getInfo", new object[] {
                        Customers,
                        Attributes,
                        AddressAttributes}, this.getInfoOperationCompleted, userState);
        }
        
        private void OngetInfoOperationCompleted(object arg) {
            if ((this.getInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInfoCompleted(this, new getInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CustomerService/2007/08#exists", RequestNamespace="urn://epages.de/WebService/CustomerService/2007/08", ResponseNamespace="urn://epages.de/WebService/CustomerService/2007/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("Customers")]
        public TExists_Return[] exists(string[] Customers) {
            object[] results = this.Invoke("exists", new object[] {
                        Customers});
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexists(string[] Customers, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exists", new object[] {
                        Customers}, callback, asyncState);
        }
        
        /// <remarks/>
        public TExists_Return[] Endexists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void existsAsync(string[] Customers) {
            this.existsAsync(Customers, null);
        }
        
        /// <remarks/>
        public void existsAsync(string[] Customers, object userState) {
            if ((this.existsOperationCompleted == null)) {
                this.existsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexistsOperationCompleted);
            }
            this.InvokeAsync("exists", new object[] {
                        Customers}, this.existsOperationCompleted, userState);
        }
        
        private void OnexistsOperationCompleted(object arg) {
            if ((this.existsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existsCompleted(this, new existsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CustomerService/2007/08#delete", RequestNamespace="urn://epages.de/WebService/CustomerService/2007/08", ResponseNamespace="urn://epages.de/WebService/CustomerService/2007/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("Customers")]
        public TDelete_Return[] delete(string[] Customers) {
            object[] results = this.Invoke("delete", new object[] {
                        Customers});
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindelete(string[] Customers, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("delete", new object[] {
                        Customers}, callback, asyncState);
        }
        
        /// <remarks/>
        public TDelete_Return[] Enddelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(string[] Customers) {
            this.deleteAsync(Customers, null);
        }
        
        /// <remarks/>
        public void deleteAsync(string[] Customers, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        Customers}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CustomerService/2007/08#update", RequestNamespace="urn://epages.de/WebService/CustomerService/2007/08", ResponseNamespace="urn://epages.de/WebService/CustomerService/2007/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("Customers")]
        public TUpdate_Return[] update(TUpdate_Input[] Customers) {
            object[] results = this.Invoke("update", new object[] {
                        Customers});
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate(TUpdate_Input[] Customers, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update", new object[] {
                        Customers}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUpdate_Return[] Endupdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(TUpdate_Input[] Customers) {
            this.updateAsync(Customers, null);
        }
        
        /// <remarks/>
        public void updateAsync(TUpdate_Input[] Customers, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        Customers}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CustomerService/2007/08#create", RequestNamespace="urn://epages.de/WebService/CustomerService/2007/08", ResponseNamespace="urn://epages.de/WebService/CustomerService/2007/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("Customers")]
        public TCreate_Return[] create(TCreate_Input[] Customers) {
            object[] results = this.Invoke("create", new object[] {
                        Customers});
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincreate(TCreate_Input[] Customers, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("create", new object[] {
                        Customers}, callback, asyncState);
        }
        
        /// <remarks/>
        public TCreate_Return[] Endcreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(TCreate_Input[] Customers) {
            this.createAsync(Customers, null);
        }
        
        /// <remarks/>
        public void createAsync(TCreate_Input[] Customers, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        Customers}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CustomerService/2007/08#find", RequestNamespace="urn://epages.de/WebService/CustomerService/2007/08", ResponseNamespace="urn://epages.de/WebService/CustomerService/2007/08")]
        [return: System.Xml.Serialization.SoapElementAttribute("Customers")]
        public string[] find(TFind_Input SearchParameters) {
            object[] results = this.Invoke("find", new object[] {
                        SearchParameters});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginfind(TFind_Input SearchParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("find", new object[] {
                        SearchParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] Endfind(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void findAsync(TFind_Input SearchParameters) {
            this.findAsync(SearchParameters, null);
        }
        
        /// <remarks/>
        public void findAsync(TFind_Input SearchParameters, object userState) {
            if ((this.findOperationCompleted == null)) {
                this.findOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindOperationCompleted);
            }
            this.InvokeAsync("find", new object[] {
                        SearchParameters}, this.findOperationCompleted, userState);
        }
        
        private void OnfindOperationCompleted(object arg) {
            if ((this.findCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findCompleted(this, new findCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerTypes/2007/08")]
    public partial class TGetInfo_Return {
        
        private string pathField;
        
        private string aliasField;
        
        private string classField;
        
        private string customerGroupField;
        
        private string taxAreaField;
        
        private string taxModelField;
        
        private string currencyIDField;
        
        private bool isHtmlEMailAllowedField;
        
        private bool isHtmlEMailAllowedFieldSpecified;
        
        private bool isDoOrderAllowedField;
        
        private bool isDoOrderAllowedFieldSpecified;
        
        private string commentField;
        
        private TAddressNamed billingAddressField;
        
        private string[] usersField;
        
        private TAttribute[] attributesField;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerGroup {
            get {
                return this.customerGroupField;
            }
            set {
                this.customerGroupField = value;
            }
        }
        
        /// <remarks/>
        public string TaxArea {
            get {
                return this.taxAreaField;
            }
            set {
                this.taxAreaField = value;
            }
        }
        
        /// <remarks/>
        public string TaxModel {
            get {
                return this.taxModelField;
            }
            set {
                this.taxModelField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHtmlEMailAllowed {
            get {
                return this.isHtmlEMailAllowedField;
            }
            set {
                this.isHtmlEMailAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsHtmlEMailAllowedSpecified {
            get {
                return this.isHtmlEMailAllowedFieldSpecified;
            }
            set {
                this.isHtmlEMailAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsDoOrderAllowed {
            get {
                return this.isDoOrderAllowedField;
            }
            set {
                this.isDoOrderAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsDoOrderAllowedSpecified {
            get {
                return this.isDoOrderAllowedFieldSpecified;
            }
            set {
                this.isDoOrderAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public TAddressNamed BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ShopTypes/2006/07")]
    public partial class TAddressNamed {
        
        private string aliasField;
        
        private string displayNameField;
        
        private string addressExtensionField;
        
        private string streetField;
        
        private string street2Field;
        
        private string zipcodeField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryIDField;
        
        private string eMailField;
        
        private string phoneField;
        
        private string faxField;
        
        private System.DateTime verifiedOnField;
        
        private bool verifiedOnFieldSpecified;
        
        private string salutationField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string eMailPrivateField;
        
        private string eMailBusinessField;
        
        private string phonePrivateField;
        
        private string phoneBusinessField;
        
        private string phoneCellField;
        
        private string genderField;
        
        private string companyField;
        
        private string departmentField;
        
        private string jobTitleField;
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string vATIDField;
        
        private string bankCodeField;
        
        private string bankNameField;
        
        private string bankAccountNoField;
        
        private string bankAccountHolderField;
        
        private string uRLField;
        
        private TAttribute[] attributesField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string AddressExtension {
            get {
                return this.addressExtensionField;
            }
            set {
                this.addressExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        public string Zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime VerifiedOn {
            get {
                return this.verifiedOnField;
            }
            set {
                this.verifiedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool VerifiedOnSpecified {
            get {
                return this.verifiedOnFieldSpecified;
            }
            set {
                this.verifiedOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string EMailPrivate {
            get {
                return this.eMailPrivateField;
            }
            set {
                this.eMailPrivateField = value;
            }
        }
        
        /// <remarks/>
        public string EMailBusiness {
            get {
                return this.eMailBusinessField;
            }
            set {
                this.eMailBusinessField = value;
            }
        }
        
        /// <remarks/>
        public string PhonePrivate {
            get {
                return this.phonePrivateField;
            }
            set {
                this.phonePrivateField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneBusiness {
            get {
                return this.phoneBusinessField;
            }
            set {
                this.phoneBusinessField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneCell {
            get {
                return this.phoneCellField;
            }
            set {
                this.phoneCellField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool BirthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VATID {
            get {
                return this.vATIDField;
            }
            set {
                this.vATIDField = value;
            }
        }
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccountNo {
            get {
                return this.bankAccountNoField;
            }
            set {
                this.bankAccountNoField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccountHolder {
            get {
                return this.bankAccountHolderField;
            }
            set {
                this.bankAccountHolderField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TAttribute {
        
        private string nameField;
        
        private string valueField;
        
        private TLocalizedValue[] localizedValuesField;
        
        private string typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] LocalizedValues {
            get {
                return this.localizedValuesField;
            }
            set {
                this.localizedValuesField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TLocalizedValue {
        
        private string languageCodeField;
        
        private string valueField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerService/2007/08")]
    public partial class TFind_Input {
        
        private string nameField;
        
        private string aliasField;
        
        private string loginField;
        
        private string eMailField;
        
        private string streetField;
        
        private string zipcodeField;
        
        private string cityField;
        
        private string customerGroupField;
        
        private float revenueField;
        
        private bool revenueFieldSpecified;
        
        private string currencyIDField;
        
        private System.DateTime revenueFromField;
        
        private bool revenueFromFieldSpecified;
        
        private System.DateTime revenueToField;
        
        private bool revenueToFieldSpecified;
        
        private string productField;
        
        private System.DateTime productFromField;
        
        private bool productFromFieldSpecified;
        
        private System.DateTime productToField;
        
        private bool productToFieldSpecified;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerGroup {
            get {
                return this.customerGroupField;
            }
            set {
                this.customerGroupField = value;
            }
        }
        
        /// <remarks/>
        public float Revenue {
            get {
                return this.revenueField;
            }
            set {
                this.revenueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool RevenueSpecified {
            get {
                return this.revenueFieldSpecified;
            }
            set {
                this.revenueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RevenueFrom {
            get {
                return this.revenueFromField;
            }
            set {
                this.revenueFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool RevenueFromSpecified {
            get {
                return this.revenueFromFieldSpecified;
            }
            set {
                this.revenueFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RevenueTo {
            get {
                return this.revenueToField;
            }
            set {
                this.revenueToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool RevenueToSpecified {
            get {
                return this.revenueToFieldSpecified;
            }
            set {
                this.revenueToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProductFrom {
            get {
                return this.productFromField;
            }
            set {
                this.productFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ProductFromSpecified {
            get {
                return this.productFromFieldSpecified;
            }
            set {
                this.productFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProductTo {
            get {
                return this.productToField;
            }
            set {
                this.productToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ProductToSpecified {
            get {
                return this.productToFieldSpecified;
            }
            set {
                this.productToFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerTypes/2007/08")]
    public partial class TCreate_Return {
        
        private string aliasField;
        
        private string pathField;
        
        private bool createdField;
        
        private bool createdFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool createdSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TError {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerTypes/2007/08")]
    public partial class TCreate_Input {
        
        private string aliasField;
        
        private string customerGroupField;
        
        private string taxAreaField;
        
        private string taxModelField;
        
        private string currencyIDField;
        
        private bool isHtmlEMailAllowedField;
        
        private bool isHtmlEMailAllowedFieldSpecified;
        
        private bool isDoOrderAllowedField;
        
        private bool isDoOrderAllowedFieldSpecified;
        
        private string commentField;
        
        private TAddressNamed billingAddressField;
        
        private string[] usersField;
        
        private TAttribute[] attributesField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerGroup {
            get {
                return this.customerGroupField;
            }
            set {
                this.customerGroupField = value;
            }
        }
        
        /// <remarks/>
        public string TaxArea {
            get {
                return this.taxAreaField;
            }
            set {
                this.taxAreaField = value;
            }
        }
        
        /// <remarks/>
        public string TaxModel {
            get {
                return this.taxModelField;
            }
            set {
                this.taxModelField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHtmlEMailAllowed {
            get {
                return this.isHtmlEMailAllowedField;
            }
            set {
                this.isHtmlEMailAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsHtmlEMailAllowedSpecified {
            get {
                return this.isHtmlEMailAllowedFieldSpecified;
            }
            set {
                this.isHtmlEMailAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsDoOrderAllowed {
            get {
                return this.isDoOrderAllowedField;
            }
            set {
                this.isDoOrderAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsDoOrderAllowedSpecified {
            get {
                return this.isDoOrderAllowedFieldSpecified;
            }
            set {
                this.isDoOrderAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public TAddressNamed BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerTypes/2007/08")]
    public partial class TUpdate_Return {
        
        private string pathField;
        
        private bool updatedField;
        
        private bool updatedFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool updatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerTypes/2007/08")]
    public partial class TUpdate_Input {
        
        private string pathField;
        
        private string customerGroupField;
        
        private string taxAreaField;
        
        private string taxModelField;
        
        private string currencyIDField;
        
        private bool isHtmlEMailAllowedField;
        
        private bool isHtmlEMailAllowedFieldSpecified;
        
        private bool isDoOrderAllowedField;
        
        private bool isDoOrderAllowedFieldSpecified;
        
        private string commentField;
        
        private TAddressNamed billingAddressField;
        
        private string[] usersField;
        
        private TAttribute[] attributesField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerGroup {
            get {
                return this.customerGroupField;
            }
            set {
                this.customerGroupField = value;
            }
        }
        
        /// <remarks/>
        public string TaxArea {
            get {
                return this.taxAreaField;
            }
            set {
                this.taxAreaField = value;
            }
        }
        
        /// <remarks/>
        public string TaxModel {
            get {
                return this.taxModelField;
            }
            set {
                this.taxModelField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHtmlEMailAllowed {
            get {
                return this.isHtmlEMailAllowedField;
            }
            set {
                this.isHtmlEMailAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsHtmlEMailAllowedSpecified {
            get {
                return this.isHtmlEMailAllowedFieldSpecified;
            }
            set {
                this.isHtmlEMailAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsDoOrderAllowed {
            get {
                return this.isDoOrderAllowedField;
            }
            set {
                this.isDoOrderAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsDoOrderAllowedSpecified {
            get {
                return this.isDoOrderAllowedFieldSpecified;
            }
            set {
                this.isDoOrderAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public TAddressNamed BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerTypes/2007/08")]
    public partial class TDelete_Return {
        
        private string pathField;
        
        private bool deletedField;
        
        private bool deletedFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool deletedSpecified {
            get {
                return this.deletedFieldSpecified;
            }
            set {
                this.deletedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CustomerTypes/2007/08")]
    public partial class TExists_Return {
        
        private string pathField;
        
        private bool existsField;
        
        private bool existsFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool existsSpecified {
            get {
                return this.existsFieldSpecified;
            }
            set {
                this.existsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getInfoCompletedEventHandler(object sender, getInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TGetInfo_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TGetInfo_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void existsCompletedEventHandler(object sender, existsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TExists_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TExists_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TDelete_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TDelete_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TUpdate_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TUpdate_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TCreate_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TCreate_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void findCompletedEventHandler(object sender, findCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591