//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3053
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace EpagesWebServices.AssignmentServiceRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_Assignment_SOAP", Namespace="urn://epages.de/WebService/AssignmentService/2005/01")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAssignedCatalog))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetCatalogsAssignedToProduct_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAssignedProduct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetProductsAssignedToCatalog_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TIsProductAssignedToCatalog_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TIsProductAssignedToCatalog_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRemoveProductFromCatalog_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRemoveProductFromCatalog_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAssignProductToCatalog_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAssignProductToCatalog_Input))]
    public partial class AssignmentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback assignProductToCatalogOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeProductFromCatalogOperationCompleted;
        
        private System.Threading.SendOrPostCallback isProductAssignedToCatalogOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProductsAssignedToCatalogOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCatalogsAssignedToProductOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AssignmentService() {
            this.Url = "http://localhost/epages/Store.soap";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event assignProductToCatalogCompletedEventHandler assignProductToCatalogCompleted;
        
        /// <remarks/>
        public event removeProductFromCatalogCompletedEventHandler removeProductFromCatalogCompleted;
        
        /// <remarks/>
        public event isProductAssignedToCatalogCompletedEventHandler isProductAssignedToCatalogCompleted;
        
        /// <remarks/>
        public event getProductsAssignedToCatalogCompletedEventHandler getProductsAssignedToCatalogCompleted;
        
        /// <remarks/>
        public event getCatalogsAssignedToProductCompletedEventHandler getCatalogsAssignedToProductCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/AssignmentService/2005/01#assignProductToCatalog", RequestNamespace="urn://epages.de/WebService/AssignmentService/2005/01", ResponseNamespace="urn://epages.de/WebService/AssignmentService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Assignments")]
        public TAssignProductToCatalog_Return[] assignProductToCatalog(TAssignProductToCatalog_Input[] Assignments) {
            object[] results = this.Invoke("assignProductToCatalog", new object[] {
                        Assignments});
            return ((TAssignProductToCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginassignProductToCatalog(TAssignProductToCatalog_Input[] Assignments, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("assignProductToCatalog", new object[] {
                        Assignments}, callback, asyncState);
        }
        
        /// <remarks/>
        public TAssignProductToCatalog_Return[] EndassignProductToCatalog(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TAssignProductToCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void assignProductToCatalogAsync(TAssignProductToCatalog_Input[] Assignments) {
            this.assignProductToCatalogAsync(Assignments, null);
        }
        
        /// <remarks/>
        public void assignProductToCatalogAsync(TAssignProductToCatalog_Input[] Assignments, object userState) {
            if ((this.assignProductToCatalogOperationCompleted == null)) {
                this.assignProductToCatalogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnassignProductToCatalogOperationCompleted);
            }
            this.InvokeAsync("assignProductToCatalog", new object[] {
                        Assignments}, this.assignProductToCatalogOperationCompleted, userState);
        }
        
        private void OnassignProductToCatalogOperationCompleted(object arg) {
            if ((this.assignProductToCatalogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.assignProductToCatalogCompleted(this, new assignProductToCatalogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/AssignmentService/2005/01#removeProductFromCatalog", RequestNamespace="urn://epages.de/WebService/AssignmentService/2005/01", ResponseNamespace="urn://epages.de/WebService/AssignmentService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Assignments")]
        public TRemoveProductFromCatalog_Return[] removeProductFromCatalog(TRemoveProductFromCatalog_Input[] Assignments) {
            object[] results = this.Invoke("removeProductFromCatalog", new object[] {
                        Assignments});
            return ((TRemoveProductFromCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginremoveProductFromCatalog(TRemoveProductFromCatalog_Input[] Assignments, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("removeProductFromCatalog", new object[] {
                        Assignments}, callback, asyncState);
        }
        
        /// <remarks/>
        public TRemoveProductFromCatalog_Return[] EndremoveProductFromCatalog(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TRemoveProductFromCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void removeProductFromCatalogAsync(TRemoveProductFromCatalog_Input[] Assignments) {
            this.removeProductFromCatalogAsync(Assignments, null);
        }
        
        /// <remarks/>
        public void removeProductFromCatalogAsync(TRemoveProductFromCatalog_Input[] Assignments, object userState) {
            if ((this.removeProductFromCatalogOperationCompleted == null)) {
                this.removeProductFromCatalogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveProductFromCatalogOperationCompleted);
            }
            this.InvokeAsync("removeProductFromCatalog", new object[] {
                        Assignments}, this.removeProductFromCatalogOperationCompleted, userState);
        }
        
        private void OnremoveProductFromCatalogOperationCompleted(object arg) {
            if ((this.removeProductFromCatalogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeProductFromCatalogCompleted(this, new removeProductFromCatalogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/AssignmentService/2005/01#isProductAssignedToCatalog", RequestNamespace="urn://epages.de/WebService/AssignmentService/2005/01", ResponseNamespace="urn://epages.de/WebService/AssignmentService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Assignments")]
        public TIsProductAssignedToCatalog_Return[] isProductAssignedToCatalog(TIsProductAssignedToCatalog_Input[] Assignments) {
            object[] results = this.Invoke("isProductAssignedToCatalog", new object[] {
                        Assignments});
            return ((TIsProductAssignedToCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisProductAssignedToCatalog(TIsProductAssignedToCatalog_Input[] Assignments, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isProductAssignedToCatalog", new object[] {
                        Assignments}, callback, asyncState);
        }
        
        /// <remarks/>
        public TIsProductAssignedToCatalog_Return[] EndisProductAssignedToCatalog(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TIsProductAssignedToCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void isProductAssignedToCatalogAsync(TIsProductAssignedToCatalog_Input[] Assignments) {
            this.isProductAssignedToCatalogAsync(Assignments, null);
        }
        
        /// <remarks/>
        public void isProductAssignedToCatalogAsync(TIsProductAssignedToCatalog_Input[] Assignments, object userState) {
            if ((this.isProductAssignedToCatalogOperationCompleted == null)) {
                this.isProductAssignedToCatalogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisProductAssignedToCatalogOperationCompleted);
            }
            this.InvokeAsync("isProductAssignedToCatalog", new object[] {
                        Assignments}, this.isProductAssignedToCatalogOperationCompleted, userState);
        }
        
        private void OnisProductAssignedToCatalogOperationCompleted(object arg) {
            if ((this.isProductAssignedToCatalogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isProductAssignedToCatalogCompleted(this, new isProductAssignedToCatalogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/AssignmentService/2005/01#getProductsAssignedToCatalog" +
            "", RequestNamespace="urn://epages.de/WebService/AssignmentService/2005/01", ResponseNamespace="urn://epages.de/WebService/AssignmentService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Assignments")]
        public TGetProductsAssignedToCatalog_Return[] getProductsAssignedToCatalog(string[] Catalogs) {
            object[] results = this.Invoke("getProductsAssignedToCatalog", new object[] {
                        Catalogs});
            return ((TGetProductsAssignedToCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetProductsAssignedToCatalog(string[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getProductsAssignedToCatalog", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TGetProductsAssignedToCatalog_Return[] EndgetProductsAssignedToCatalog(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetProductsAssignedToCatalog_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void getProductsAssignedToCatalogAsync(string[] Catalogs) {
            this.getProductsAssignedToCatalogAsync(Catalogs, null);
        }
        
        /// <remarks/>
        public void getProductsAssignedToCatalogAsync(string[] Catalogs, object userState) {
            if ((this.getProductsAssignedToCatalogOperationCompleted == null)) {
                this.getProductsAssignedToCatalogOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProductsAssignedToCatalogOperationCompleted);
            }
            this.InvokeAsync("getProductsAssignedToCatalog", new object[] {
                        Catalogs}, this.getProductsAssignedToCatalogOperationCompleted, userState);
        }
        
        private void OngetProductsAssignedToCatalogOperationCompleted(object arg) {
            if ((this.getProductsAssignedToCatalogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProductsAssignedToCatalogCompleted(this, new getProductsAssignedToCatalogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/AssignmentService/2005/01#getCatalogsAssignedToProduct" +
            "", RequestNamespace="urn://epages.de/WebService/AssignmentService/2005/01", ResponseNamespace="urn://epages.de/WebService/AssignmentService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Assignments")]
        public TGetCatalogsAssignedToProduct_Return[] getCatalogsAssignedToProduct(string[] Products) {
            object[] results = this.Invoke("getCatalogsAssignedToProduct", new object[] {
                        Products});
            return ((TGetCatalogsAssignedToProduct_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCatalogsAssignedToProduct(string[] Products, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCatalogsAssignedToProduct", new object[] {
                        Products}, callback, asyncState);
        }
        
        /// <remarks/>
        public TGetCatalogsAssignedToProduct_Return[] EndgetCatalogsAssignedToProduct(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetCatalogsAssignedToProduct_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void getCatalogsAssignedToProductAsync(string[] Products) {
            this.getCatalogsAssignedToProductAsync(Products, null);
        }
        
        /// <remarks/>
        public void getCatalogsAssignedToProductAsync(string[] Products, object userState) {
            if ((this.getCatalogsAssignedToProductOperationCompleted == null)) {
                this.getCatalogsAssignedToProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCatalogsAssignedToProductOperationCompleted);
            }
            this.InvokeAsync("getCatalogsAssignedToProduct", new object[] {
                        Products}, this.getCatalogsAssignedToProductOperationCompleted, userState);
        }
        
        private void OngetCatalogsAssignedToProductOperationCompleted(object arg) {
            if ((this.getCatalogsAssignedToProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCatalogsAssignedToProductCompleted(this, new getCatalogsAssignedToProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TAssignProductToCatalog_Input {
        
        private string catalogField;
        
        private string productField;
        
        private string positionField;
        
        /// <remarks/>
        public string Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TAssignedCatalog {
        
        private string pathField;
        
        private bool assignedField;
        
        private bool assignedWithParentField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool assigned {
            get {
                return this.assignedField;
            }
            set {
                this.assignedField = value;
            }
        }
        
        /// <remarks/>
        public bool assignedWithParent {
            get {
                return this.assignedWithParentField;
            }
            set {
                this.assignedWithParentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TGetCatalogsAssignedToProduct_Return {
        
        private string productField;
        
        private TAssignedCatalog[] catalogsField;
        
        private TError errorField;
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public TAssignedCatalog[] Catalogs {
            get {
                return this.catalogsField;
            }
            set {
                this.catalogsField = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TError {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TAssignedProduct {
        
        private string pathField;
        
        private string positionField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TGetProductsAssignedToCatalog_Return {
        
        private string catalogField;
        
        private TAssignedProduct[] productsField;
        
        private TError errorField;
        
        /// <remarks/>
        public string Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public TAssignedProduct[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TIsProductAssignedToCatalog_Return {
        
        private string catalogField;
        
        private string productField;
        
        private bool assignedField;
        
        private bool assignedFieldSpecified;
        
        private bool assignedWithParentField;
        
        private bool assignedWithParentFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public bool assigned {
            get {
                return this.assignedField;
            }
            set {
                this.assignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool assignedSpecified {
            get {
                return this.assignedFieldSpecified;
            }
            set {
                this.assignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool assignedWithParent {
            get {
                return this.assignedWithParentField;
            }
            set {
                this.assignedWithParentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool assignedWithParentSpecified {
            get {
                return this.assignedWithParentFieldSpecified;
            }
            set {
                this.assignedWithParentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TIsProductAssignedToCatalog_Input {
        
        private string catalogField;
        
        private string productField;
        
        /// <remarks/>
        public string Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TRemoveProductFromCatalog_Return {
        
        private string catalogField;
        
        private string productField;
        
        private bool removedField;
        
        private bool removedFieldSpecified;
        
        private bool assignedWithParentField;
        
        private bool assignedWithParentFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public bool removed {
            get {
                return this.removedField;
            }
            set {
                this.removedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool removedSpecified {
            get {
                return this.removedFieldSpecified;
            }
            set {
                this.removedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool assignedWithParent {
            get {
                return this.assignedWithParentField;
            }
            set {
                this.assignedWithParentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool assignedWithParentSpecified {
            get {
                return this.assignedWithParentFieldSpecified;
            }
            set {
                this.assignedWithParentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TRemoveProductFromCatalog_Input {
        
        private string catalogField;
        
        private string productField;
        
        /// <remarks/>
        public string Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/AssignmentTypes/2005/01")]
    public partial class TAssignProductToCatalog_Return {
        
        private string catalogField;
        
        private string productField;
        
        private bool assignedField;
        
        private bool assignedFieldSpecified;
        
        private bool assignedWithParentField;
        
        private bool assignedWithParentFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public bool assigned {
            get {
                return this.assignedField;
            }
            set {
                this.assignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool assignedSpecified {
            get {
                return this.assignedFieldSpecified;
            }
            set {
                this.assignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool assignedWithParent {
            get {
                return this.assignedWithParentField;
            }
            set {
                this.assignedWithParentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool assignedWithParentSpecified {
            get {
                return this.assignedWithParentFieldSpecified;
            }
            set {
                this.assignedWithParentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void assignProductToCatalogCompletedEventHandler(object sender, assignProductToCatalogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class assignProductToCatalogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal assignProductToCatalogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TAssignProductToCatalog_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TAssignProductToCatalog_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void removeProductFromCatalogCompletedEventHandler(object sender, removeProductFromCatalogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeProductFromCatalogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeProductFromCatalogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRemoveProductFromCatalog_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRemoveProductFromCatalog_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void isProductAssignedToCatalogCompletedEventHandler(object sender, isProductAssignedToCatalogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isProductAssignedToCatalogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isProductAssignedToCatalogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIsProductAssignedToCatalog_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIsProductAssignedToCatalog_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getProductsAssignedToCatalogCompletedEventHandler(object sender, getProductsAssignedToCatalogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProductsAssignedToCatalogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProductsAssignedToCatalogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TGetProductsAssignedToCatalog_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TGetProductsAssignedToCatalog_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getCatalogsAssignedToProductCompletedEventHandler(object sender, getCatalogsAssignedToProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCatalogsAssignedToProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCatalogsAssignedToProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TGetCatalogsAssignedToProduct_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TGetCatalogsAssignedToProduct_Return[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591