//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3053
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace EpagesWebServices.UserServiceRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_User_SOAP", Namespace="urn://epages.de/WebService/UserService/2005/01")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TDelete_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TExists_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TLocalizedValue))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAttribute))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetInfo_Return))]
    public partial class UserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback existsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserService() {
            this.Url = "http://localhost/epages/Store.soap";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getInfoCompletedEventHandler getInfoCompleted;
        
        /// <remarks/>
        public event existsCompletedEventHandler existsCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/UserService/2005/01#getInfo", RequestNamespace="urn://epages.de/WebService/UserService/2005/01", ResponseNamespace="urn://epages.de/WebService/UserService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Users")]
        public TGetInfo_Return[] getInfo(string[] Users, string[] Attributes) {
            object[] results = this.Invoke("getInfo", new object[] {
                        Users,
                        Attributes});
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInfo(string[] Users, string[] Attributes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInfo", new object[] {
                        Users,
                        Attributes}, callback, asyncState);
        }
        
        /// <remarks/>
        public TGetInfo_Return[] EndgetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void getInfoAsync(string[] Users, string[] Attributes) {
            this.getInfoAsync(Users, Attributes, null);
        }
        
        /// <remarks/>
        public void getInfoAsync(string[] Users, string[] Attributes, object userState) {
            if ((this.getInfoOperationCompleted == null)) {
                this.getInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInfoOperationCompleted);
            }
            this.InvokeAsync("getInfo", new object[] {
                        Users,
                        Attributes}, this.getInfoOperationCompleted, userState);
        }
        
        private void OngetInfoOperationCompleted(object arg) {
            if ((this.getInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInfoCompleted(this, new getInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/UserService/2005/01#exists", RequestNamespace="urn://epages.de/WebService/UserService/2005/01", ResponseNamespace="urn://epages.de/WebService/UserService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Users")]
        public TExists_Return[] exists(string[] Users) {
            object[] results = this.Invoke("exists", new object[] {
                        Users});
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexists(string[] Users, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exists", new object[] {
                        Users}, callback, asyncState);
        }
        
        /// <remarks/>
        public TExists_Return[] Endexists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void existsAsync(string[] Users) {
            this.existsAsync(Users, null);
        }
        
        /// <remarks/>
        public void existsAsync(string[] Users, object userState) {
            if ((this.existsOperationCompleted == null)) {
                this.existsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexistsOperationCompleted);
            }
            this.InvokeAsync("exists", new object[] {
                        Users}, this.existsOperationCompleted, userState);
        }
        
        private void OnexistsOperationCompleted(object arg) {
            if ((this.existsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existsCompleted(this, new existsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/UserService/2005/01#delete", RequestNamespace="urn://epages.de/WebService/UserService/2005/01", ResponseNamespace="urn://epages.de/WebService/UserService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Users")]
        public TDelete_Return[] delete(string[] Users) {
            object[] results = this.Invoke("delete", new object[] {
                        Users});
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindelete(string[] Users, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("delete", new object[] {
                        Users}, callback, asyncState);
        }
        
        /// <remarks/>
        public TDelete_Return[] Enddelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(string[] Users) {
            this.deleteAsync(Users, null);
        }
        
        /// <remarks/>
        public void deleteAsync(string[] Users, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        Users}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/UserService/2005/01#update", RequestNamespace="urn://epages.de/WebService/UserService/2005/01", ResponseNamespace="urn://epages.de/WebService/UserService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Users")]
        public TUpdate_Return[] update(TUpdate_Input[] Users) {
            object[] results = this.Invoke("update", new object[] {
                        Users});
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate(TUpdate_Input[] Users, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update", new object[] {
                        Users}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUpdate_Return[] Endupdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(TUpdate_Input[] Users) {
            this.updateAsync(Users, null);
        }
        
        /// <remarks/>
        public void updateAsync(TUpdate_Input[] Users, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        Users}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/UserService/2005/01#create", RequestNamespace="urn://epages.de/WebService/UserService/2005/01", ResponseNamespace="urn://epages.de/WebService/UserService/2005/01")]
        [return: System.Xml.Serialization.SoapElementAttribute("Users")]
        public TCreate_Return[] create(TCreate_Input[] Users) {
            object[] results = this.Invoke("create", new object[] {
                        Users});
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincreate(TCreate_Input[] Users, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("create", new object[] {
                        Users}, callback, asyncState);
        }
        
        /// <remarks/>
        public TCreate_Return[] Endcreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(TCreate_Input[] Users) {
            this.createAsync(Users, null);
        }
        
        /// <remarks/>
        public void createAsync(TCreate_Input[] Users, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        Users}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/UserTypes/2005/01")]
    public partial class TGetInfo_Return {
        
        private string pathField;
        
        private string aliasField;
        
        private string classField;
        
        private string localeIDField;
        
        private string languageCodeField;
        
        private string currencyIDField;
        
        private string passwordField;
        
        private bool isActivatedField;
        
        private bool isActivatedFieldSpecified;
        
        private bool deleteConfirmationField;
        
        private bool deleteConfirmationFieldSpecified;
        
        private bool isLoginCookieAllowedField;
        
        private bool isLoginCookieAllowedFieldSpecified;
        
        private bool isHtmlEMailAllowedField;
        
        private bool isHtmlEMailAllowedFieldSpecified;
        
        private string reminderQuestionField;
        
        private string challengePhraseField;
        
        private string eMailField;
        
        private string nameField;
        
        private TAddress billingAddressField;
        
        private TAddress shippingAddressField;
        
        private string[] customersField;
        
        private TAttribute[] attributesField;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActivated {
            get {
                return this.isActivatedField;
            }
            set {
                this.isActivatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsActivatedSpecified {
            get {
                return this.isActivatedFieldSpecified;
            }
            set {
                this.isActivatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DeleteConfirmation {
            get {
                return this.deleteConfirmationField;
            }
            set {
                this.deleteConfirmationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool DeleteConfirmationSpecified {
            get {
                return this.deleteConfirmationFieldSpecified;
            }
            set {
                this.deleteConfirmationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsLoginCookieAllowed {
            get {
                return this.isLoginCookieAllowedField;
            }
            set {
                this.isLoginCookieAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsLoginCookieAllowedSpecified {
            get {
                return this.isLoginCookieAllowedFieldSpecified;
            }
            set {
                this.isLoginCookieAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsHtmlEMailAllowed {
            get {
                return this.isHtmlEMailAllowedField;
            }
            set {
                this.isHtmlEMailAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsHtmlEMailAllowedSpecified {
            get {
                return this.isHtmlEMailAllowedFieldSpecified;
            }
            set {
                this.isHtmlEMailAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ReminderQuestion {
            get {
                return this.reminderQuestionField;
            }
            set {
                this.reminderQuestionField = value;
            }
        }
        
        /// <remarks/>
        public string ChallengePhrase {
            get {
                return this.challengePhraseField;
            }
            set {
                this.challengePhraseField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TAddress BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public TAddress ShippingAddress {
            get {
                return this.shippingAddressField;
            }
            set {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string[] Customers {
            get {
                return this.customersField;
            }
            set {
                this.customersField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ShopTypes/2005/01")]
    public partial class TAddress {
        
        private string displayNameField;
        
        private string addressExtensionField;
        
        private string streetField;
        
        private string zipcodeField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryIDField;
        
        private string eMailField;
        
        private string phoneField;
        
        private string faxField;
        
        private System.DateTime verifiedOnField;
        
        private bool verifiedOnFieldSpecified;
        
        private string salutationField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string eMailPrivateField;
        
        private string eMailBusinessField;
        
        private string phonePrivateField;
        
        private string phoneBusinessField;
        
        private string phoneCellField;
        
        private string genderField;
        
        private string companyField;
        
        private string departmentField;
        
        private string jobTitleField;
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string vATIDField;
        
        private string bankCodeField;
        
        private string bankNameField;
        
        private string bankAccountNoField;
        
        private string bankAccountHolderField;
        
        private string uRLField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string AddressExtension {
            get {
                return this.addressExtensionField;
            }
            set {
                this.addressExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime VerifiedOn {
            get {
                return this.verifiedOnField;
            }
            set {
                this.verifiedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool VerifiedOnSpecified {
            get {
                return this.verifiedOnFieldSpecified;
            }
            set {
                this.verifiedOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string EMailPrivate {
            get {
                return this.eMailPrivateField;
            }
            set {
                this.eMailPrivateField = value;
            }
        }
        
        /// <remarks/>
        public string EMailBusiness {
            get {
                return this.eMailBusinessField;
            }
            set {
                this.eMailBusinessField = value;
            }
        }
        
        /// <remarks/>
        public string PhonePrivate {
            get {
                return this.phonePrivateField;
            }
            set {
                this.phonePrivateField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneBusiness {
            get {
                return this.phoneBusinessField;
            }
            set {
                this.phoneBusinessField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneCell {
            get {
                return this.phoneCellField;
            }
            set {
                this.phoneCellField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool BirthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VATID {
            get {
                return this.vATIDField;
            }
            set {
                this.vATIDField = value;
            }
        }
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccountNo {
            get {
                return this.bankAccountNoField;
            }
            set {
                this.bankAccountNoField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccountHolder {
            get {
                return this.bankAccountHolderField;
            }
            set {
                this.bankAccountHolderField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/UserTypes/2005/01")]
    public partial class TCreate_Return {
        
        private string aliasField;
        
        private string pathField;
        
        private bool createdField;
        
        private bool createdFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool createdSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TError {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/UserTypes/2005/01")]
    public partial class TCreate_Input {
        
        private string aliasField;
        
        private string localeIDField;
        
        private string languageCodeField;
        
        private string currencyIDField;
        
        private string passwordField;
        
        private bool isActivatedField;
        
        private bool isActivatedFieldSpecified;
        
        private bool deleteConfirmationField;
        
        private bool deleteConfirmationFieldSpecified;
        
        private bool isLoginCookieAllowedField;
        
        private bool isLoginCookieAllowedFieldSpecified;
        
        private bool isHtmlEMailAllowedField;
        
        private bool isHtmlEMailAllowedFieldSpecified;
        
        private string reminderQuestionField;
        
        private string challengePhraseField;
        
        private string eMailField;
        
        private string nameField;
        
        private TAddress billingAddressField;
        
        private TAddress shippingAddressField;
        
        private string[] customersField;
        
        private TAttribute[] attributesField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActivated {
            get {
                return this.isActivatedField;
            }
            set {
                this.isActivatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsActivatedSpecified {
            get {
                return this.isActivatedFieldSpecified;
            }
            set {
                this.isActivatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DeleteConfirmation {
            get {
                return this.deleteConfirmationField;
            }
            set {
                this.deleteConfirmationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool DeleteConfirmationSpecified {
            get {
                return this.deleteConfirmationFieldSpecified;
            }
            set {
                this.deleteConfirmationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsLoginCookieAllowed {
            get {
                return this.isLoginCookieAllowedField;
            }
            set {
                this.isLoginCookieAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsLoginCookieAllowedSpecified {
            get {
                return this.isLoginCookieAllowedFieldSpecified;
            }
            set {
                this.isLoginCookieAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsHtmlEMailAllowed {
            get {
                return this.isHtmlEMailAllowedField;
            }
            set {
                this.isHtmlEMailAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsHtmlEMailAllowedSpecified {
            get {
                return this.isHtmlEMailAllowedFieldSpecified;
            }
            set {
                this.isHtmlEMailAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ReminderQuestion {
            get {
                return this.reminderQuestionField;
            }
            set {
                this.reminderQuestionField = value;
            }
        }
        
        /// <remarks/>
        public string ChallengePhrase {
            get {
                return this.challengePhraseField;
            }
            set {
                this.challengePhraseField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TAddress BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public TAddress ShippingAddress {
            get {
                return this.shippingAddressField;
            }
            set {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string[] Customers {
            get {
                return this.customersField;
            }
            set {
                this.customersField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TAttribute {
        
        private string nameField;
        
        private string valueField;
        
        private TLocalizedValue[] localizedValuesField;
        
        private string typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] LocalizedValues {
            get {
                return this.localizedValuesField;
            }
            set {
                this.localizedValuesField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TLocalizedValue {
        
        private string languageCodeField;
        
        private string valueField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/UserTypes/2005/01")]
    public partial class TUpdate_Return {
        
        private string pathField;
        
        private bool updatedField;
        
        private bool updatedFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool updatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/UserTypes/2005/01")]
    public partial class TUpdate_Input {
        
        private string pathField;
        
        private string localeIDField;
        
        private string languageCodeField;
        
        private string currencyIDField;
        
        private string passwordField;
        
        private bool isActivatedField;
        
        private bool isActivatedFieldSpecified;
        
        private bool deleteConfirmationField;
        
        private bool deleteConfirmationFieldSpecified;
        
        private bool isLoginCookieAllowedField;
        
        private bool isLoginCookieAllowedFieldSpecified;
        
        private bool isHtmlEMailAllowedField;
        
        private bool isHtmlEMailAllowedFieldSpecified;
        
        private string reminderQuestionField;
        
        private string challengePhraseField;
        
        private string eMailField;
        
        private string nameField;
        
        private TAddress billingAddressField;
        
        private TAddress shippingAddressField;
        
        private string[] customersField;
        
        private TAttribute[] attributesField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActivated {
            get {
                return this.isActivatedField;
            }
            set {
                this.isActivatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsActivatedSpecified {
            get {
                return this.isActivatedFieldSpecified;
            }
            set {
                this.isActivatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DeleteConfirmation {
            get {
                return this.deleteConfirmationField;
            }
            set {
                this.deleteConfirmationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool DeleteConfirmationSpecified {
            get {
                return this.deleteConfirmationFieldSpecified;
            }
            set {
                this.deleteConfirmationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsLoginCookieAllowed {
            get {
                return this.isLoginCookieAllowedField;
            }
            set {
                this.isLoginCookieAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsLoginCookieAllowedSpecified {
            get {
                return this.isLoginCookieAllowedFieldSpecified;
            }
            set {
                this.isLoginCookieAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsHtmlEMailAllowed {
            get {
                return this.isHtmlEMailAllowedField;
            }
            set {
                this.isHtmlEMailAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsHtmlEMailAllowedSpecified {
            get {
                return this.isHtmlEMailAllowedFieldSpecified;
            }
            set {
                this.isHtmlEMailAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ReminderQuestion {
            get {
                return this.reminderQuestionField;
            }
            set {
                this.reminderQuestionField = value;
            }
        }
        
        /// <remarks/>
        public string ChallengePhrase {
            get {
                return this.challengePhraseField;
            }
            set {
                this.challengePhraseField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TAddress BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public TAddress ShippingAddress {
            get {
                return this.shippingAddressField;
            }
            set {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string[] Customers {
            get {
                return this.customersField;
            }
            set {
                this.customersField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/UserTypes/2005/01")]
    public partial class TDelete_Return {
        
        private string pathField;
        
        private bool deletedField;
        
        private bool deletedFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool deletedSpecified {
            get {
                return this.deletedFieldSpecified;
            }
            set {
                this.deletedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/UserTypes/2005/01")]
    public partial class TExists_Return {
        
        private string pathField;
        
        private bool existsField;
        
        private bool existsFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool existsSpecified {
            get {
                return this.existsFieldSpecified;
            }
            set {
                this.existsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getInfoCompletedEventHandler(object sender, getInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TGetInfo_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TGetInfo_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void existsCompletedEventHandler(object sender, existsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TExists_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TExists_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TDelete_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TDelete_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TUpdate_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TUpdate_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TCreate_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TCreate_Return[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591