//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3053
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace EpagesWebServices.CatalogService3Ref {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_Catalog_SOAP", Namespace="urn://epages.de/WebService/CatalogService/2008/11")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TSortProducts_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TSortProducts_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TUpdate_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TDelete_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TExists_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TAttribute))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TLocalizedValue))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetInfo_Return))]
    public partial class CatalogService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback existsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRootOperationCompleted;
        
        private System.Threading.SendOrPostCallback sortProductsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CatalogService() {
            this.Url = "http://localhost/epages/Store.soap";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getInfoCompletedEventHandler getInfoCompleted;
        
        /// <remarks/>
        public event existsCompletedEventHandler existsCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event getRootCompletedEventHandler getRootCompleted;
        
        /// <remarks/>
        public event sortProductsCompletedEventHandler sortProductsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2008/11#getInfo", RequestNamespace="urn://epages.de/WebService/CatalogService/2008/11", ResponseNamespace="urn://epages.de/WebService/CatalogService/2008/11")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TGetInfo_Return[] getInfo(string[] Catalogs, string[] Attributes, string[] LanguageCodes) {
            object[] results = this.Invoke("getInfo", new object[] {
                        Catalogs,
                        Attributes,
                        LanguageCodes});
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInfo(string[] Catalogs, string[] Attributes, string[] LanguageCodes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInfo", new object[] {
                        Catalogs,
                        Attributes,
                        LanguageCodes}, callback, asyncState);
        }
        
        /// <remarks/>
        public TGetInfo_Return[] EndgetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void getInfoAsync(string[] Catalogs, string[] Attributes, string[] LanguageCodes) {
            this.getInfoAsync(Catalogs, Attributes, LanguageCodes, null);
        }
        
        /// <remarks/>
        public void getInfoAsync(string[] Catalogs, string[] Attributes, string[] LanguageCodes, object userState) {
            if ((this.getInfoOperationCompleted == null)) {
                this.getInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInfoOperationCompleted);
            }
            this.InvokeAsync("getInfo", new object[] {
                        Catalogs,
                        Attributes,
                        LanguageCodes}, this.getInfoOperationCompleted, userState);
        }
        
        private void OngetInfoOperationCompleted(object arg) {
            if ((this.getInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInfoCompleted(this, new getInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2008/11#exists", RequestNamespace="urn://epages.de/WebService/CatalogService/2008/11", ResponseNamespace="urn://epages.de/WebService/CatalogService/2008/11")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TExists_Return[] exists(string[] Catalogs) {
            object[] results = this.Invoke("exists", new object[] {
                        Catalogs});
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexists(string[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exists", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TExists_Return[] Endexists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void existsAsync(string[] Catalogs) {
            this.existsAsync(Catalogs, null);
        }
        
        /// <remarks/>
        public void existsAsync(string[] Catalogs, object userState) {
            if ((this.existsOperationCompleted == null)) {
                this.existsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexistsOperationCompleted);
            }
            this.InvokeAsync("exists", new object[] {
                        Catalogs}, this.existsOperationCompleted, userState);
        }
        
        private void OnexistsOperationCompleted(object arg) {
            if ((this.existsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existsCompleted(this, new existsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2008/11#delete", RequestNamespace="urn://epages.de/WebService/CatalogService/2008/11", ResponseNamespace="urn://epages.de/WebService/CatalogService/2008/11")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TDelete_Return[] delete(string[] Catalogs) {
            object[] results = this.Invoke("delete", new object[] {
                        Catalogs});
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindelete(string[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("delete", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TDelete_Return[] Enddelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(string[] Catalogs) {
            this.deleteAsync(Catalogs, null);
        }
        
        /// <remarks/>
        public void deleteAsync(string[] Catalogs, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        Catalogs}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2008/11#update", RequestNamespace="urn://epages.de/WebService/CatalogService/2008/11", ResponseNamespace="urn://epages.de/WebService/CatalogService/2008/11")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TUpdate_Return[] update(TUpdate_Input[] Catalogs) {
            object[] results = this.Invoke("update", new object[] {
                        Catalogs});
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate(TUpdate_Input[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TUpdate_Return[] Endupdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TUpdate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(TUpdate_Input[] Catalogs) {
            this.updateAsync(Catalogs, null);
        }
        
        /// <remarks/>
        public void updateAsync(TUpdate_Input[] Catalogs, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        Catalogs}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2008/11#create", RequestNamespace="urn://epages.de/WebService/CatalogService/2008/11", ResponseNamespace="urn://epages.de/WebService/CatalogService/2008/11")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TCreate_Return[] create(TCreate_Input[] Catalogs) {
            object[] results = this.Invoke("create", new object[] {
                        Catalogs});
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincreate(TCreate_Input[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("create", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TCreate_Return[] Endcreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(TCreate_Input[] Catalogs) {
            this.createAsync(Catalogs, null);
        }
        
        /// <remarks/>
        public void createAsync(TCreate_Input[] Catalogs, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        Catalogs}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2008/11#getRoot", RequestNamespace="urn://epages.de/WebService/CatalogService/2008/11", ResponseNamespace="urn://epages.de/WebService/CatalogService/2008/11")]
        [return: System.Xml.Serialization.SoapElementAttribute("Root")]
        public TGetRoot_Return getRoot() {
            object[] results = this.Invoke("getRoot", new object[0]);
            return ((TGetRoot_Return)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRoot(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRoot", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TGetRoot_Return EndgetRoot(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetRoot_Return)(results[0]));
        }
        
        /// <remarks/>
        public void getRootAsync() {
            this.getRootAsync(null);
        }
        
        /// <remarks/>
        public void getRootAsync(object userState) {
            if ((this.getRootOperationCompleted == null)) {
                this.getRootOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRootOperationCompleted);
            }
            this.InvokeAsync("getRoot", new object[0], this.getRootOperationCompleted, userState);
        }
        
        private void OngetRootOperationCompleted(object arg) {
            if ((this.getRootCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRootCompleted(this, new getRootCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/CatalogService/2008/11#sortProducts", RequestNamespace="urn://epages.de/WebService/CatalogService/2008/11", ResponseNamespace="urn://epages.de/WebService/CatalogService/2008/11")]
        [return: System.Xml.Serialization.SoapElementAttribute("Catalogs")]
        public TSortProducts_Return[] sortProducts(TSortProducts_Input[] Catalogs) {
            object[] results = this.Invoke("sortProducts", new object[] {
                        Catalogs});
            return ((TSortProducts_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsortProducts(TSortProducts_Input[] Catalogs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sortProducts", new object[] {
                        Catalogs}, callback, asyncState);
        }
        
        /// <remarks/>
        public TSortProducts_Return[] EndsortProducts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TSortProducts_Return[])(results[0]));
        }
        
        /// <remarks/>
        public void sortProductsAsync(TSortProducts_Input[] Catalogs) {
            this.sortProductsAsync(Catalogs, null);
        }
        
        /// <remarks/>
        public void sortProductsAsync(TSortProducts_Input[] Catalogs, object userState) {
            if ((this.sortProductsOperationCompleted == null)) {
                this.sortProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsortProductsOperationCompleted);
            }
            this.InvokeAsync("sortProducts", new object[] {
                        Catalogs}, this.sortProductsOperationCompleted, userState);
        }
        
        private void OnsortProductsOperationCompleted(object arg) {
            if ((this.sortProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sortProductsCompleted(this, new sortProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TGetInfo_Return {
        
        private string pathField;
        
        private string aliasField;
        
        private string classField;
        
        private string positionField;
        
        private string parentCatalogField;
        
        private string webUrlField;
        
        private bool isVisibleField;
        
        private bool isVisibleFieldSpecified;
        
        private TLocalizedValue[] nameField;
        
        private TLocalizedValue[] textField;
        
        private TLocalizedValue[] text1Field;
        
        private TLocalizedValue[] text2Field;
        
        private TLocalizedValue[] text3Field;
        
        private string[] subCatalogsField;
        
        private TAttribute[] templateTypesField;
        
        private TAttribute[] attributesField;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string ParentCatalog {
            get {
                return this.parentCatalogField;
            }
            set {
                this.parentCatalogField = value;
            }
        }
        
        /// <remarks/>
        public string WebUrl {
            get {
                return this.webUrlField;
            }
            set {
                this.webUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsVisibleSpecified {
            get {
                return this.isVisibleFieldSpecified;
            }
            set {
                this.isVisibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text1 {
            get {
                return this.text1Field;
            }
            set {
                this.text1Field = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text2 {
            get {
                return this.text2Field;
            }
            set {
                this.text2Field = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text3 {
            get {
                return this.text3Field;
            }
            set {
                this.text3Field = value;
            }
        }
        
        /// <remarks/>
        public string[] SubCatalogs {
            get {
                return this.subCatalogsField;
            }
            set {
                this.subCatalogsField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] TemplateTypes {
            get {
                return this.templateTypesField;
            }
            set {
                this.templateTypesField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TLocalizedValue {
        
        private string languageCodeField;
        
        private string valueField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TSortProducts_Return {
        
        private string pathField;
        
        private bool sortedField;
        
        private bool sortedFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool sorted {
            get {
                return this.sortedField;
            }
            set {
                this.sortedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool sortedSpecified {
            get {
                return this.sortedFieldSpecified;
            }
            set {
                this.sortedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TError {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TSortProducts_Input {
        
        private string pathField;
        
        private string sortField;
        
        private bool allSubField;
        
        private bool allSubFieldSpecified;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
            }
        }
        
        /// <remarks/>
        public bool allSub {
            get {
                return this.allSubField;
            }
            set {
                this.allSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool allSubSpecified {
            get {
                return this.allSubFieldSpecified;
            }
            set {
                this.allSubFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogService/2008/11")]
    public partial class TGetRoot_Return {
        
        private string pathField;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TCreate_Return {
        
        private string aliasField;
        
        private string parentCatalogField;
        
        private string pathField;
        
        private bool createdField;
        
        private bool createdFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string ParentCatalog {
            get {
                return this.parentCatalogField;
            }
            set {
                this.parentCatalogField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool createdSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TCreate_Input {
        
        private string aliasField;
        
        private string parentCatalogField;
        
        private bool isVisibleField;
        
        private bool isVisibleFieldSpecified;
        
        private string positionField;
        
        private TLocalizedValue[] nameField;
        
        private TLocalizedValue[] textField;
        
        private TLocalizedValue[] text1Field;
        
        private TLocalizedValue[] text2Field;
        
        private TLocalizedValue[] text3Field;
        
        private TAttribute[] templateTypesField;
        
        private TAttribute[] attributesField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string ParentCatalog {
            get {
                return this.parentCatalogField;
            }
            set {
                this.parentCatalogField = value;
            }
        }
        
        /// <remarks/>
        public bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsVisibleSpecified {
            get {
                return this.isVisibleFieldSpecified;
            }
            set {
                this.isVisibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text1 {
            get {
                return this.text1Field;
            }
            set {
                this.text1Field = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text2 {
            get {
                return this.text2Field;
            }
            set {
                this.text2Field = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text3 {
            get {
                return this.text3Field;
            }
            set {
                this.text3Field = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] TemplateTypes {
            get {
                return this.templateTypesField;
            }
            set {
                this.templateTypesField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TAttribute {
        
        private string nameField;
        
        private string valueField;
        
        private TLocalizedValue[] localizedValuesField;
        
        private string typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] LocalizedValues {
            get {
                return this.localizedValuesField;
            }
            set {
                this.localizedValuesField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TUpdate_Return {
        
        private string pathField;
        
        private bool updatedField;
        
        private bool updatedFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool updatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TUpdate_Input {
        
        private string pathField;
        
        private bool isVisibleField;
        
        private bool isVisibleFieldSpecified;
        
        private string positionField;
        
        private TLocalizedValue[] nameField;
        
        private TLocalizedValue[] textField;
        
        private TLocalizedValue[] text1Field;
        
        private TLocalizedValue[] text2Field;
        
        private TLocalizedValue[] text3Field;
        
        private TAttribute[] templateTypesField;
        
        private TAttribute[] attributesField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsVisibleSpecified {
            get {
                return this.isVisibleFieldSpecified;
            }
            set {
                this.isVisibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text1 {
            get {
                return this.text1Field;
            }
            set {
                this.text1Field = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text2 {
            get {
                return this.text2Field;
            }
            set {
                this.text2Field = value;
            }
        }
        
        /// <remarks/>
        public TLocalizedValue[] Text3 {
            get {
                return this.text3Field;
            }
            set {
                this.text3Field = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] TemplateTypes {
            get {
                return this.templateTypesField;
            }
            set {
                this.templateTypesField = value;
            }
        }
        
        /// <remarks/>
        public TAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TDelete_Return {
        
        private string pathField;
        
        private bool deletedField;
        
        private bool deletedFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool deletedSpecified {
            get {
                return this.deletedFieldSpecified;
            }
            set {
                this.deletedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/CatalogTypes/2008/11")]
    public partial class TExists_Return {
        
        private string pathField;
        
        private bool existsField;
        
        private bool existsFieldSpecified;
        
        private TError errorField;
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool existsSpecified {
            get {
                return this.existsFieldSpecified;
            }
            set {
                this.existsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getInfoCompletedEventHandler(object sender, getInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TGetInfo_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TGetInfo_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void existsCompletedEventHandler(object sender, existsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TExists_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TExists_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TDelete_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TDelete_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TUpdate_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TUpdate_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TCreate_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TCreate_Return[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getRootCompletedEventHandler(object sender, getRootCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRootCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRootCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TGetRoot_Return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TGetRoot_Return)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void sortProductsCompletedEventHandler(object sender, sortProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sortProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sortProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSortProducts_Return[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSortProducts_Return[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591