//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpagesWebServices.ProductBundleServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_ProductBundle_SOAP", Namespace="urn://epages.de/WebService/ProductBundleService/2007/07")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetInfo_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TExists_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TExists_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TDelete_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TBundledProductPath))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TDelete_Input))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Return))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TBundledProduct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TCreate_Input))]
    public partial class ProductBundleService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ProductBundleService() {
            this.Url = "http://localhost/epages/Store.soap";
        }
        
        public ProductBundleService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductBundleService/2007/07#create", RequestNamespace="urn://epages.de/WebService/ProductBundleService/2007/07", ResponseNamespace="urn://epages.de/WebService/ProductBundleService/2007/07")]
        [return: System.Xml.Serialization.SoapElementAttribute("ProductBundles")]
        public TCreate_Return[] create(TCreate_Input[] ProductBundles) {
            object[] results = this.Invoke("create", new object[] {
                        ProductBundles});
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincreate(TCreate_Input[] ProductBundles, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("create", new object[] {
                        ProductBundles}, callback, asyncState);
        }
        
        /// <remarks/>
        public TCreate_Return[] Endcreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TCreate_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductBundleService/2007/07#delete", RequestNamespace="urn://epages.de/WebService/ProductBundleService/2007/07", ResponseNamespace="urn://epages.de/WebService/ProductBundleService/2007/07")]
        [return: System.Xml.Serialization.SoapElementAttribute("ProductBundles")]
        public TDelete_Return[] delete(TDelete_Input[] ProductBundles) {
            object[] results = this.Invoke("delete", new object[] {
                        ProductBundles});
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindelete(TDelete_Input[] ProductBundles, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("delete", new object[] {
                        ProductBundles}, callback, asyncState);
        }
        
        /// <remarks/>
        public TDelete_Return[] Enddelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TDelete_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductBundleService/2007/07#exists", RequestNamespace="urn://epages.de/WebService/ProductBundleService/2007/07", ResponseNamespace="urn://epages.de/WebService/ProductBundleService/2007/07")]
        [return: System.Xml.Serialization.SoapElementAttribute("ProductBundles")]
        public TExists_Return[] exists(TExists_Input[] ProductBundles) {
            object[] results = this.Invoke("exists", new object[] {
                        ProductBundles});
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexists(TExists_Input[] ProductBundles, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exists", new object[] {
                        ProductBundles}, callback, asyncState);
        }
        
        /// <remarks/>
        public TExists_Return[] Endexists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TExists_Return[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ProductBundleService/2007/07#getInfo", RequestNamespace="urn://epages.de/WebService/ProductBundleService/2007/07", ResponseNamespace="urn://epages.de/WebService/ProductBundleService/2007/07")]
        [return: System.Xml.Serialization.SoapElementAttribute("ProductBundles")]
        public TGetInfo_Return[] getInfo(string[] Products) {
            object[] results = this.Invoke("getInfo", new object[] {
                        Products});
            return ((TGetInfo_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInfo(string[] Products, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInfo", new object[] {
                        Products}, callback, asyncState);
        }
        
        /// <remarks/>
        public TGetInfo_Return[] EndgetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetInfo_Return[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TCreate_Input {
        
        /// <remarks/>
        public string Product;
        
        /// <remarks/>
        public TBundledProduct[] BundledProducts;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TBundledProduct {
        
        /// <remarks/>
        public string Path;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Position;
        
        /// <remarks/>
        public float Quantity;
        
        /// <remarks/>
        public string Alias;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TGetInfo_Return {
        
        /// <remarks/>
        public string Product;
        
        /// <remarks/>
        public TBundledProduct[] BundledProducts;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/EpagesTypes/2005/01")]
    public partial class TError {
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TExists_Return {
        
        /// <remarks/>
        public string Product;
        
        /// <remarks/>
        public string BundledProduct;
        
        /// <remarks/>
        public bool exists;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool existsSpecified;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TExists_Input {
        
        /// <remarks/>
        public string Product;
        
        /// <remarks/>
        public string BundledProduct;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TDelete_Return {
        
        /// <remarks/>
        public string Product;
        
        /// <remarks/>
        public bool deleted;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool deletedSpecified;
        
        /// <remarks/>
        public TError Error;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TBundledProductPath {
        
        /// <remarks/>
        public string Path;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TDelete_Input {
        
        /// <remarks/>
        public string Product;
        
        /// <remarks/>
        public TBundledProductPath[] BundledProductPaths;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ProductBundleTypes/2007/07")]
    public partial class TCreate_Return {
        
        /// <remarks/>
        public string Product;
        
        /// <remarks/>
        public bool created;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool createdSpecified;
        
        /// <remarks/>
        public TError Error;
    }
}
