//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpagesWebServices.ShippingMethodServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_ShippingMethod_SOAP", Namespace="urn://epages.de/WebService/ShippingMethodService/2008/03")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TGetList_Return))]
    public partial class ShippingMethodService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ShippingMethodService() {
            this.Url = "http://localhost/epages/Store.soap";
        }
        
        public ShippingMethodService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/ShippingMethodService/2008/03#getList", RequestNamespace="urn://epages.de/WebService/ShippingMethodService/2008/03", ResponseNamespace="urn://epages.de/WebService/ShippingMethodService/2008/03")]
        [return: System.Xml.Serialization.SoapElementAttribute("ShippingMethods")]
        public TGetList_Return[] getList() {
            object[] results = this.Invoke("getList", new object[0]);
            return ((TGetList_Return[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TGetList_Return[] EndgetList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TGetList_Return[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/ShippingMethodTypes/2008/03")]
    public partial class TGetList_Return {
        
        /// <remarks/>
        public string Path;
    }
}
