//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpagesProviderWebServices.SimpleProvisioningServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bind_SimpleProvisioning_SOAP", Namespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
    public partial class SimpleProvisioningService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SimpleProvisioningService() {
            this.Url = "http://localhost/epages/Site.soap";
        }
        
        public SimpleProvisioningService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/SimpleProvisioningService/2009/10#create", RequestNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10", ResponseNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
        public void create(TCreateShop CreateShopData) {
            this.Invoke("create", new object[] {
                        CreateShopData});
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincreate(TCreateShop CreateShopData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("create", new object[] {
                        CreateShopData}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endcreate(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/SimpleProvisioningService/2009/10#markForDeletion", RequestNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10", ResponseNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
        public void markForDeletion(TShopRef ShopRef) {
            this.Invoke("markForDeletion", new object[] {
                        ShopRef});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmarkForDeletion(TShopRef ShopRef, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("markForDeletion", new object[] {
                        ShopRef}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmarkForDeletion(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/SimpleProvisioningService/2009/10#exists", RequestNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10", ResponseNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
        [return: System.Xml.Serialization.SoapElementAttribute("Exists")]
        public bool exists(TShopRef ShopRef) {
            object[] results = this.Invoke("exists", new object[] {
                        ShopRef});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexists(TShopRef ShopRef, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exists", new object[] {
                        ShopRef}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endexists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/SimpleProvisioningService/2009/10#update", RequestNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10", ResponseNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
        public void update(TUpdateShop ShopData) {
            this.Invoke("update", new object[] {
                        ShopData});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate(TUpdateShop ShopData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update", new object[] {
                        ShopData}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endupdate(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/SimpleProvisioningService/2009/10#getInfo", RequestNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10", ResponseNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
        [return: System.Xml.Serialization.SoapElementAttribute("ShopInfo")]
        public TInfoShop getInfo(TShopRef ShopRef) {
            object[] results = this.Invoke("getInfo", new object[] {
                        ShopRef});
            return ((TInfoShop)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInfo(TShopRef ShopRef, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInfo", new object[] {
                        ShopRef}, callback, asyncState);
        }
        
        /// <remarks/>
        public TInfoShop EndgetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TInfoShop)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn://epages.de/WebService/SimpleProvisioningService/2009/10#rename", RequestNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10", ResponseNamespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
        public void rename(TRename_Input ShopInfo) {
            this.Invoke("rename", new object[] {
                        ShopInfo});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginrename(TRename_Input ShopInfo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("rename", new object[] {
                        ShopInfo}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endrename(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
    public partial class TCreateShop {
        
        /// <remarks/>
        public string Alias;
        
        /// <remarks/>
        public string ShopType;
        
        /// <remarks/>
        public bool IsClosed;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsClosedSpecified;
        
        /// <remarks/>
        public bool IsTrialShop;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsTrialShopSpecified;
        
        /// <remarks/>
        public bool IsInternalTestShop;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsInternalTestShopSpecified;
        
        /// <remarks/>
        public string DomainName;
        
        /// <remarks/>
        public bool HasSSLCertificate;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool HasSSLCertificateSpecified;
        
        /// <remarks/>
        public string MerchantLogin;
        
        /// <remarks/>
        public string MerchantPassword;
        
        /// <remarks/>
        public string MerchantEMail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
    public partial class TRename_Input {
        
        /// <remarks/>
        public string Alias;
        
        /// <remarks/>
        public string NewAlias;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
    public partial class TInfoShop {
        
        /// <remarks/>
        public string Alias;
        
        /// <remarks/>
        public string ShopType;
        
        /// <remarks/>
        public string Database;
        
        /// <remarks/>
        public bool IsClosed;
        
        /// <remarks/>
        public bool IsDeleted;
        
        /// <remarks/>
        public bool IsTrialShop;
        
        /// <remarks/>
        public bool IsInternalTestShop;
        
        /// <remarks/>
        public string DomainName;
        
        /// <remarks/>
        public bool HasSSLCertificate;
        
        /// <remarks/>
        public string MerchantLogin;
        
        /// <remarks/>
        public string MerchantEMail;
        
        /// <remarks/>
        public System.DateTime LastMerchantLoginDate;
        
        /// <remarks/>
        public bool IsMarkedForDel;
        
        /// <remarks/>
        public string StorefrontURL;
        
        /// <remarks/>
        public string BackofficeURL;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
    public partial class TUpdateShop {
        
        /// <remarks/>
        public string Alias;
        
        /// <remarks/>
        public string ShopType;
        
        /// <remarks/>
        public bool IsClosed;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsClosedSpecified;
        
        /// <remarks/>
        public bool IsTrialShop;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsTrialShopSpecified;
        
        /// <remarks/>
        public bool IsInternalTestShop;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsInternalTestShopSpecified;
        
        /// <remarks/>
        public string DomainName;
        
        /// <remarks/>
        public bool HasSSLCertificate;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool HasSSLCertificateSpecified;
        
        /// <remarks/>
        public string MerchantLogin;
        
        /// <remarks/>
        public string MerchantPassword;
        
        /// <remarks/>
        public string MerchantEMail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn://epages.de/WebService/SimpleProvisioningService/2009/10")]
    public partial class TShopRef {
        
        /// <remarks/>
        public string Alias;
    }
}
